[velociraptor_linux]
velo_linux ansible_host=192.168.1.2 ansible_user=user ansible_password=resu

[velociraptor_linux:vars]
ansible_become=true
ansible_become_method=sudo
ansible_become_password=resu
